# Generated by Django 4.1.3 on 2022-12-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_cook_time_recipe_photo_recipe_prep_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredientName',
        ),
    ]
