# Generated by Django 4.1.3 on 2022-12-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_name_ingredient_ingredientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
